# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 555)
        MainWindow.setMinimumSize(QtCore.QSize(799, 555))
        MainWindow.setMaximumSize(QtCore.QSize(799, 555))
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setStyleSheet("border-image: url(./visual/fondo.jpeg);")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnHand = QtWidgets.QPushButton(self.centralwidget)
        self.btnHand.setGeometry(QtCore.QRect(420, 340, 191, 111))
        self.btnHand.setStyleSheet("border-image: url(./visual/HG.png);")
        self.btnHand.setText("")
        self.btnHand.setObjectName("btnHand")
        self.btnFace = QtWidgets.QPushButton(self.centralwidget)
        self.btnFace.setGeometry(QtCore.QRect(160, 340, 191, 111))
        self.btnFace.setStyleSheet("border-image: url(./visual/FR.png);")
        self.btnFace.setText("")
        self.btnFace.setObjectName("btnFace")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HF Recognition"))
from visual import *
